# Generated by Django 3.0.3 on 2020-02-23 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_hourssettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hourssettings',
            old_name='contact',
            new_name='hours',
        ),
    ]
