# Generated by Django 3.0.3 on 2020-02-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site_settings', '0004_auto_20200223_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterCTASettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=250)),
                ('button_text', models.CharField(default='Contact Us', max_length=25)),
                ('button_external_page', models.URLField(blank=True, help_text='If an internal page is selected, it will be used before the external page.')),
                ('button_internal_page', models.ForeignKey(blank=True, help_text='If an internal page is selected, it will be used before the external page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
